include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    prefer_final_locals: true
    always_declare_return_types: true
    avoid_print: true
    avoid_empty_else: true
    avoid_types_on_closure_parameters: true
    annotate_overrides: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    directives_ordering: true
    file_names: true
    hash_and_equals: true
    no_duplicate_case_values: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_this: true
