// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuJMjTFO3F4E9keOjs1_1o-tA4nVNOUjk',
    appId: '1:1008674270054:web:eccfdf019566a3507cb6a7',
    messagingSenderId: '1008674270054',
    projectId: 'big-food-5b613',
    authDomain: 'big-food-5b613.firebaseapp.com',
    storageBucket: 'big-food-5b613.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuJMjTFO3F4E9keOjs1_1o-tA4nVNOUjk',
    appId: '1:1008674270054:android:eccfdf019566a3507cb6a7',
    messagingSenderId: '1008674270054',
    projectId: 'big-food-5b613',
    storageBucket: 'big-food-5b613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuJMjTFO3F4E9keOjs1_1o-tA4nVNOUjk',
    appId: '1:1008674270054:ios:eccfdf019566a3507cb6a7',
    messagingSenderId: '1008674270054',
    projectId: 'big-food-5b613',
    storageBucket: 'big-food-5b613.appspot.com',
    iosBundleId: 'com.example.caredify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuJMjTFO3F4E9keOjs1_1o-tA4nVNOUjk',
    appId: '1:1008674270054:macos:eccfdf019566a3507cb6a7',
    messagingSenderId: '1008674270054',
    projectId: 'big-food-5b613',
    storageBucket: 'big-food-5b613.appspot.com',
    iosBundleId: 'com.example.caredify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuJMjTFO3F4E9keOjs1_1o-tA4nVNOUjk',
    appId: '1:1008674270054:windows:eccfdf019566a3507cb6a7',
    messagingSenderId: '1008674270054',
    projectId: 'big-food-5b613',
    storageBucket: 'big-food-5b613.appspot.com',
  );
}
