name: Build and Analyze

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localization files
        run: flutter gen-l10n

      - name: Generate stub firebase_options.dart
        run: |
          mkdir -p lib
          echo "// ignore_for_file: type=lint" > lib/firebase_options.dart
          echo "import 'package:firebase_core/firebase_core.dart';" >> lib/firebase_options.dart
          echo "class DefaultFirebaseOptions {" >> lib/firebase_options.dart
          echo "  static FirebaseOptions get currentPlatform => throw UnimplementedError('FirebaseOptions are not available in CI.');" >> lib/firebase_options.dart
          echo "}" >> lib/firebase_options.dart

      - name: Analyze Dart code  
        run: flutter analyze
      - name: Set up Firebase (stub initialization)
        run: |
          echo "// Stub Firebase initialization for test" > test/firebase_setup_test.dart
          echo "import 'package:firebase_core/firebase_core.dart';" >> test/firebase_setup_test.dart
          echo "Future<void> setupFirebase() async => await Firebase.initializeApp();" >> test/firebase_setup_test.dart
          echo "void main() {}" >> test/firebase_setup_test.dart

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localization files
        run: flutter gen-l10n

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Set up JDK 17 for SonarCloud
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check Dart version
        run: dart --version

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: Saif-Yahyaoui_caredify
          SONAR_ORGANIZATION: saif-yahyaoui
